# Docker Compose file for easier build and test in local machine
version: "3.7"
services:
  main_app:
    build:
      context: .
    network_mode: host
    image: fw_mainapp:latest
    command: python3 app/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true
  webhook_app:
    build:
      context: .
    network_mode: host
    image: fw_webhook:latest
    command: python3 app/webhook.py
    ports:
      - "5001:5001"
    volumes:
      - .:/app
  engineio_app:
    build:
      context: .
    network_mode: host
    image: fw_engineio:latest
    command: python3 app/engineio.py
    ports:
      - "5002:5002"
    volumes:
      - .:/app